import { Grid } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

import Layout from "../components/Layout/Layout";
const Product: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout showSide={false}>
        <Grid container direction={"column"} justifyContent={"center"}>
          <Grid item>
            <p style={{ textAlign: "center" }}>heelo</p>
          </Grid>
        </Grid>
      </Layout>
    </div>
  );
};

export default Product;
