import type { NextPage } from "next";
import Head from "next/head";
import MainContant from "../components/Content/Content";
import Layout from "../components/Layout/Layout";
import { InferGetStaticPropsType } from "next";
import { categorie, product } from "../interfaces/products_data";
import { GetStaticProps } from "next";

export const getStaticProps: GetStaticProps = async () => {
  const categoriesres = await fetch(
    `${process.env.API_URL}/api/v1/departments`
  );
  const topproductsres = await fetch(
    `${process.env.API_URL}/api/v1/products/toprated`
  );
  const categoriesdata = await categoriesres.json();
  const topproductsdata = await topproductsres.json();

  const categories: Array<categorie> = await categoriesdata.data;
  const topproducts: Array<product> = await topproductsdata.data;
  return {
    props: {
      categories,
      topproducts,
    },
  };
};

const Home: NextPage = ({
  categories,
  topproducts,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout showSide={true} categories={categories}>
        <MainContant data={topproducts} />
      </Layout>
    </div>
  );
};

export default Home;
